### ISSUE TITLE
Increase Cooldown or lower duration of stone form

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/whos_going_to_win#4]
![image](https://user-images.githubusercontent.com/16277198/82833276-ea6c3d80-9f00-11ea-9e6e-95ea1743c550.png)
Stone form ability is very powerful makes these guys almost impossible to kill. If two fight each other, the match will time out. Either double the cooldown or lower the duration of the stone form.

**Comment by ZLOY5** [comment]
Cooldown increased to 30 sec
