### ISSUE TITLE
Ability display is broken

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/whos_going_to_win#9]
![image](https://user-images.githubusercontent.com/16277198/83311529-d7d06c00-a252-11ea-8649-01644c400429.png)

**Comment by ZLOY5** [comment]
What display resolution you have?
Because I have no issue
![image](https://user-images.githubusercontent.com/10956575/83322661-4832b980-a262-11ea-99b5-a6cc534b6223.png)

**Comment by ZLOY5** [comment]
You should check this, maked some changes to styles
